"""empty message

Revision ID: 640dc706c4b0
Revises: 144cb687aed9
Create Date: 2023-01-13 13:12:33.231248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640dc706c4b0'
down_revision = '144cb687aed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
